language: php
sudo: false
dist: trusty

env:
  global:
    - RUN_PHPCS="no"
    - RUN_SCRUTINIZER="no"
    - COMPOSER_FLAGS="--prefer-stable"
    - PHPUNIT_FLAGS=""
    - INSTALL_APCU="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: RUN_PHPCS="yes" RUN_SCRUTINIZER="yes" PHPUNIT_FLAGS="--coverage-clover .travis/logs/clover.xml"
    - php: 7.3
    - php: 7.3
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.4snapshot
      env: INSTALL_MEMCACHED="no"
    - php: nightly
      env: INSTALL_MEMCACHED="no"
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

services:
  - memcached
  - redis-server

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS
  - if [ "RUN_SCRUTINIZER" == "yes" ]; then composer require --no-update satooshi/php-coveralls:~1.0; fi
  # Enable additional PHP extensions
  - if [[ $INSTALL_APCU == "yes" ]]; then phpenv config-add .travis/phpenv/apcu.ini; fi
  - if [[ $INSTALL_MEMCACHED == "yes" ]]; then phpenv config-add .travis/phpenv/memcached.ini; fi
  - if [[ $INSTALL_REDIS == "yes" ]]; then phpenv config-add .travis/phpenv/redis.ini; fi

script:
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then mkdir -p .travis/logs; fi
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$RUN_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover .travis/logs/clover.xml; fi
  - if [[ $RUN_PHPCS == "yes" ]]; then vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards && vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/; fi;

after_script:
  - php vendor/bin/coveralls -v
